---
# tasks file for roles/ubuntu-confignagios

- name: download nagios-4.4.5.tar.gz
  get_url:
    url: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.5.tar.gz
    dest: /tmp/nagios-4.4.5.tar.gz

- name: unarchive nagios-4.4.5.tar.gz
  unarchive:
    src: /tmp/nagios-4.4.5.tar.gz
    dest: /tmp/
    remote_src: yes
  register: unarchive_nagios

- name: configure nagios core to use apache as the web server
  shell:
    chdir: /tmp/nagios-4.4.5
    cmd: "./comfigure --with-httpd-conf=/etc/apache2/sites-enabled"
  when: unarchive_nagios.changed

- name: Compile the main nagios program and CGIs
  make:
    chdir: /tmp/nagios-4.4.5
    target: all
  when: unarchive_nagios.changed

- name: create nagios core user and group
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-groups-users
  when: unarchive_nagios.changed

- name: add the user to the apache web server group
  user:
    name: ubuntu-nagios-crebello
    comment: New user for nagios
    group: www-data
    append: yes

- name: install nagios core mai program, CGIs, and html files
  make:
    chdir: /tmp/nagios-4.4.5
    target: install
  when: unarchive_nagios.changed

- name: install nagios core startup scripts
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-init
  when: unarchive_nagios.changed

- name: initialize the init scripts
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-daemoinit
  when: unarchive_nagios.changed

- name: install and configure permissions on the directory for holding the nagios core external command file
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-commandmode
  when: unarchive_nagios.changed

- name: install nagios core sample configuration files in /usr/local/nagios/etc
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-webconf
  when: unarchive_nagios.changed

- name: install apache configuration file for the nagios web interface
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-webconf
  when: unarchive_nagios.changed

- name: enable apache2 rewrite
  apache2_module:
    state: present
    name: rewrite

- name: download nagios plugins
  get_url:
    url: https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.3.3/nagios-plugins-2.3
    dest: /tmp/
  register: download_plugins

- name: extract the nagios plugins
  unarchive:
    src: /tmp/nagios-plugins-2.3.3.tar.gz
    dest: /tmp/
    remote_src: yes
  when: download_plugins.changed

- name: compile nagios plugins
  shell:
    chdir: /tmp/nagios-plugins-2.3.3
    cmd: "./configure"
  when: download_plugins.changed

- name: build the default nagios plugins
  make:
    chdir: tmp/nagios-plugins-2.3.3/
  when: download_plugins.changed

- name: install in nagios plugins
  make:
    chdir: /tmp/nagios-plugins-2.3.3/
    target: install
  when: download_plugins.changed

- name: comfigure nagios core web interface basic authentication
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: ubuntu-admin-crebello
    password: crebello26
#     crypt_scheme: md5_crypt
  register: config-auth

- name: eneble and start nagios
  systemd:
    name: nagios
    state: started
    enabled: yes

- name: restart and enable apache2
  systemd:
    name: apache2
    state: restarted
    enabled: yes
  when: config_auth.changed

