---
# tasks file for roles/centos_es

- name: install vsftpd
  yum:
    name: vsftpd
    state: latest
    update_cache: yes

- name: stop firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: creating ftp user
  user:
    name: cmbcrebello-tip01
    password: $5$r/WDml.YKuZuTABo$uXsWqegBTcPUbycly3Et/zS413m9IP7
    comment: "ftp user"

- name: adding deny user
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "DenyUsers cmbcrebello-tip01"
  register: sshd_config

- name: restarting sshd service
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed

- name: creating ftp dir
  file:
    path: /home/cmbcrebello-tip01/ftp
    state: directory
    owner: cmbcrebello-tip01
    group: cmbcrebello-tip01

- name: creating ftp dir files
  file:
    path: /home/cmbcrebello-tip01/ftp/files
    state: directory
    owner: cmbcrebello-tip01
    group: cmbcrebello-tip01

- name: copying vsftpd.conf
  copy:
    src: vsftpd.conf
    dest: /etc/vsftpd.conf
  register: vsftpd_config

- name: restarting vsftpd.conf
  service:
    name: vsftpd
    state: restarted
  when: vsftpd_config.changed
