---
# tasks file for roles/ubuntu-Nagios
#- name: update and upgrade apt packages
#  apt:
#    update_cache: yes
#    upgrade: 'yes'

- name: install prerequisite of nagios core
  apt:
    name:
      - autoconf
      - gcc
      - libc6
      - make
      - wget
      - unzip
      - apache2
      - php
      - libapache2-mod-php
      - libgd-dev
    state: latest
    update_cache: yes

- name: download nagios-4.4.5
  get_url:
    url: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.5.tar.gz
    dest: /tmp/nagios-4.4.5.tar.gz

- name: unrchive nagios-4.4.5
  unarchive:
    src: /tmp/nagios-4.4.5.tar.gz
    dest: /tmp/
    remote_src: yes
  register: unarchive_nagios

- name: configure nagios core to use apache as the web server
  shell:
    chdir: /tmp/nagios-4.4.5
    cmb: "./configure --with-httpd-conf=/etc/apache2/sites-enabled"
  when: unarchive_nagios,changed

- name: compile the main nagios program and cgis
  make:
    chdir: /tmp/nagios-4.4.5
    target: all
  when: unarchive_nagios.changed

- name: create nagios core user and group
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-groups-users
  when: unarchive_nagios.changed

- name: add the user to the apache web server group
  user:
    name: ubuntu-nagios-cynaa
    comment: New user for nagios
    group: www-data
    append: yes

- name: install nagios core main program, cgis, ans html files
  make:
    chdir: /tmp/nagios-4.4.5
    target: install
  when: unarchive_nagios.changed

- name: install nagios core startup scripts
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-iniy
  when: unarchive_nagios.changed

- name: initialize the init scripts
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-daemoninit
  when: unarchive_nagios.changed

- name: install and configure premission on the dirctory
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-commandmode
  when: unarchive_nagios.changed

- name: install nagios core sample configuration files in /usr/local/nagios/etc
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-config
  when: unarchive_nagios.changed

- name: install apache config file for nagios web interface
  make:
    chdir: /tmp/nagios-4.4.5
    target: install-webconf
  when: unarchive_nagios.changed

- name: enable apache2 rewrite
  apache2_module:
    state: present
    name: rewrite

- name: enable apache2 cgi
  apache2_module:
    state: present
    name: cgi

- name: download nagios plugins
  get_url:
    url: https://github.com/nagios-plugins/nagios-plugins/releases/download/release-2.3.3/nagios-plugins-2.3.3.tar.gz
    dest: /tmp/
  register: download_plugins

- name: extract the nagios plugins
  unrachive:
    src: /tmp/nagios-plugins-2.3.3.tar.gz
    dest: /tmp/
    remore_src: yes
  when: download_plugins.changed

- name: compile nagios plugins
  shell:
    chdir: /tmp/nagios-plugins-2.3.3
    cmd: "./configure"
  when: download_plugins.changed

- name: build the defaults nagios plugins
  make:
    chdir: /tmp/nagios-plugins-2.3.3/
    target: install
  when: download_plugins.changed

- name: install in  nagios plugins
  make:
    chdir: /tmp/nagios-plugins-2.3.3/
    target: install
  when: download_plugins.changed

- name: configure nagios core web interface basic authentication
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: ubuntu-admin-cynaa
    password: crebello26
#     crypt_scheme: md5_crypt
  register: config_auth

- name: enable and start nagios
  systemd:
    name: nagios
    state: started
    enabled: yes

- name: restart and enable apache2
  systemd:
    name: apache2
    state: started
    enabled: yes
  when: config_auth.changed



