---
# Stop Firewall
- name: stop firewall service on unbuntu and centos
  hosts: all
  tasks:
    - name: stop ufw on ubuntu
      service:
        name: ufw
        state: stopped
        enabled: no
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: stop firewall on centos
      service:
        name: firewall
        state: stopped
        enabled: no
      when: ansible_distribution == 'CentoOS' or ansible_distribution == 'Red Hat Enterprise Linux'

#Nagios
- hosts: nagios
  tasks:
    - name: install and configure on ubuntu
      include_role:
        name: ubuntu-Nagios
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: install and configure nagios on centos
      include_role:
        name: centos-Nagios
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

#Grafana
- hosts: grafana
  tasks:
    - name: install and configure grafana on ubuntu
      include_role:
        name: ubuntu-Grafana
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: install and configure grafana on centos
      include_role:
        name: centos-Grafana
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

#Prometheus
- hosts: prometheus
  tasks:
    - name: install and configure prometheus on ubuntu
      include_role:
        name: ubuntu-Prometheus
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: install and configure prometheus on centos
      include_role:
        name: centos-Prometheus
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

#Influxdb
- hosts: influxdb
  tasks:
    - name: install and configure influxdb on ubuntu
      include_role:
        name: ubuntu-Influxdb
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: install and configure influxdb on centos
      include_role:
        name: centos-Influxdb
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

#Httpd and PHP
- hosts: httpd_php
  tasks:
    - name: install apache2 and php on ubuntu
      include_role:
        name: ubuntu-Apache2_php
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: install httpd and php on centos
      include_role:
        name: centos-Httpd_php
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

#Mariadb
- hosts: mariadb
  tasks:
    - name: install mariadb on ubuntu
      include_role:
        name: ubuntu-Mariadb
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: install on centos
      include_role:
        name: centos-Mariadb
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

#install and configure Elastic Stack (Elasticsearch, Kibana and Logstash) on ubuntu and centos
- hosts: elasticsearch
  tasks:
    - name: install and configure elasticsearch on ubuntu
      include_role:
        name: ubuntu-Elasticsearch
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: install and configure elasticsearch on centos
      include_role:
        name: centos-Elasticsearch
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- hosts: kibana
  tasks:
    - name: install and configure kibana on ubuntu
      include_role:
        name: ubuntu-Kibana
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: install and configure kibana on centos
      include_role:
        name: centos-Kibana
      when: ansible_distribution == 'CantOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- host: logstash
  tasks:
    - name: install and configure logstash on ubuntu
      include_role:
        name: ubuntu-Logstash
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: install and configure logstash on centos
      include_role:
        name: centos-Logstash
      when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Eneterprise Linux'
