---
- name: installing packegas in ubuntu
  hosts: ubuntu
  vars_files:
    - ./config.yaml
  roles:
    - ubuntu_es
    - ubuntu_git
    - ubuntu_mt
    - ubuntu_motd

- name: installing packages in centos
  hosts: centos
  vars_files:
    - ./config.yaml
  roles:
    - centos_es
    - centos_git
    - centos_mt
    - centos_motd

- name: installing packages in opensuse
  hosts: opensuse
  vars_files:
    - ./config.yaml
  roles:
    - opensuse_es
    - opensuse_git
    - opensuse_mt
    - opensuse_motd
