---
# tasks file for roles/centos-Kibana

- name: install kibana using dnf
  dnf:
    name: kibana
    state: present

- name: configure server port
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '#server.port$'
    line: 'server.port: 5601'

- nane: cofigure server host
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '#server.host$'
    line: 'elasticsearch.host: [http://localhost:9200]'

- name: configure elasticsearch hosts
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '#elasticserch.hosts$'
    line: 'elasticsearch.hosts: [http://localhost:9200]'

- name: start kibana
  systemd:
    name: kibana
    state: started
    enabled: yes

- name: allow traffic on port 5601
  firewalld:
    port: 5601/tcp
    permanent: true
    state: enabled
  register: allowed_port

- name: reload firewall service
  systemd:
    name: firewalld
    state: restarted
    deamon_reload: yes
  when: allowed_port.changed
    
