---
# tasks file for roles/opensuse_es

- name: install vsftpd
  zypper:
    name: vsftpd
    state: latest
    update_cache: yes

- name: stop firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: creating ftp user
  user:
    name: cmbcrebello-tip01
    password: $5$H9.6c.i2jlrXCYbJ$gB1pYlefgQCagsrfnH1aanT4reK4uwO7amP39H7YSXA
    comment: "ftp user"

- name: creating ftp group
  group:
    name: cmbcrebello-tip01

- name: adding deny user
  lineinfile:
    path: /etc/ssh/sshd_config
    line: "DenyUsers cmbcrebello-tip01"
  register: sshd_config

- name: restarting sshd service
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed

- name: creating ftp dir
  file:
    path: /home/cmbcrebello-tip01/ftp
    state: directory
    owner: cmbcrebello-tip01
    group: cmbcrebello-tip01

- name: creating ftp dir file
  file:
    path: /home/cmbcrebello-tip01/ftp/files
    state: directory
    owner: cmbcrebello-tip01
    group: cmbcrebello-tip01

- name: copying vsftpd
  copy:
    src: vsftpd.conf
    dest: /etc/vsftpd.conf
  register: vsftpd_config

- name: deleting line in vsftpd.conf
  lineinfile:
    path: /etc/vsftpd.conf
    regexp: 'secure_chroot_dir=/var/run/vsftpd/empty'
    line: ' '

- name: restarting vsftpd.conf
  service:
    name: vsftpd
    state: started
  when: vsftpd_config.changed
